/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/KITABATAKEAKIFUMI/src/github.com/akif999/prototypes/nim/practice/fizzbazz/nimcache/fizzbazz.o /Users/KITABATAKEAKIFUMI/src/github.com/akif999/prototypes/nim/practice/fizzbazz/nimcache/fizzbazz.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, fizzbazzDatInit000)(void);
NI i_f49apVimjIcS5LfTBEqs69aA;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_3n0zGhTD6IJIea9aE5fxsmQ_3, "fizzbuzz", 8);
STRING_LITERAL(TM_3n0zGhTD6IJIea9aE5fxsmQ_5, "fizz", 4);
STRING_LITERAL(TM_3n0zGhTD6IJIea9aE5fxsmQ_7, "buzz", 4);

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	fizzbazzDatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}


static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("fizzbazz", "fizzbazz.nim");
	{
		NI res;
		nimln_(1973, "system.nim");
		res = ((NI) 1);
		{
			nimln_(1974, "system.nim");
			while (1) {
				NI TM_3n0zGhTD6IJIea9aE5fxsmQ_8;
				if (!(res <= ((NI) 100))) goto LA3;
				nimln_(1975, "system.nim");
				i_f49apVimjIcS5LfTBEqs69aA = res;
				nimln_(2, "fizzbazz.nim");
				{
					NI TM_3n0zGhTD6IJIea9aE5fxsmQ_2;
					TM_3n0zGhTD6IJIea9aE5fxsmQ_2 = modInt(i_f49apVimjIcS5LfTBEqs69aA, ((NI) 15));
					if (!(((NI) ((NI)(TM_3n0zGhTD6IJIea9aE5fxsmQ_2))) == ((NI) 0))) goto LA6_;
					nimln_(3, "fizzbazz.nim");
					printf("%s\012", ((NimStringDesc*) &TM_3n0zGhTD6IJIea9aE5fxsmQ_3)? (((NimStringDesc*) &TM_3n0zGhTD6IJIea9aE5fxsmQ_3))->data:"nil");
					fflush(stdout);
				}
				goto LA4_;
				LA6_: ;
				{
					NI TM_3n0zGhTD6IJIea9aE5fxsmQ_4;
					nimln_(4, "fizzbazz.nim");
					TM_3n0zGhTD6IJIea9aE5fxsmQ_4 = modInt(i_f49apVimjIcS5LfTBEqs69aA, ((NI) 3));
					if (!(((NI) ((NI)(TM_3n0zGhTD6IJIea9aE5fxsmQ_4))) == ((NI) 0))) goto LA9_;
					nimln_(5, "fizzbazz.nim");
					printf("%s\012", ((NimStringDesc*) &TM_3n0zGhTD6IJIea9aE5fxsmQ_5)? (((NimStringDesc*) &TM_3n0zGhTD6IJIea9aE5fxsmQ_5))->data:"nil");
					fflush(stdout);
				}
				goto LA4_;
				LA9_: ;
				{
					NI TM_3n0zGhTD6IJIea9aE5fxsmQ_6;
					nimln_(6, "fizzbazz.nim");
					TM_3n0zGhTD6IJIea9aE5fxsmQ_6 = modInt(i_f49apVimjIcS5LfTBEqs69aA, ((NI) 5));
					if (!(((NI) ((NI)(TM_3n0zGhTD6IJIea9aE5fxsmQ_6))) == ((NI) 0))) goto LA12_;
					nimln_(7, "fizzbazz.nim");
					printf("%s\012", ((NimStringDesc*) &TM_3n0zGhTD6IJIea9aE5fxsmQ_7)? (((NimStringDesc*) &TM_3n0zGhTD6IJIea9aE5fxsmQ_7))->data:"nil");
					fflush(stdout);
				}
				goto LA4_;
				LA12_: ;
				{
					NimStringDesc* T15_;
					nimln_(9, "fizzbazz.nim");
					T15_ = (NimStringDesc*)0;
					T15_ = nimIntToStr(i_f49apVimjIcS5LfTBEqs69aA);
					printf("%s\012", T15_? (T15_)->data:"nil");
					fflush(stdout);
				}
				LA4_: ;
				nimln_(1976, "system.nim");
				TM_3n0zGhTD6IJIea9aE5fxsmQ_8 = addInt(res, ((NI) 1));
				res = (NI)(TM_3n0zGhTD6IJIea9aE5fxsmQ_8);
			} LA3: ;
		}
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, fizzbazzDatInit000)(void) {
}

